on:
  push:
    branchs:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: kirikiriyamama
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/kirikiriyamama/imagemagick
          tags: type=sha,prefix=,format=long
          flavor: "latest=true"
      - name: build-and-push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
